export interface IIconProps {
  color?: string;
  size?: number | string;
};


export type TIconName =
  "ActivitySquare" |
  "AddressBook" |
  "AngleBotton" |
  "AngleDown" |
  "AngleDownSmall" |
  "AngleDownThick" |
  "AngleLeftSmall" |
  "AngleRight" |
  "AnglesDown" |
  "AnglesDownSmall" |
  "ArrowDownFromLine" |
  "ArrowDownSmall" |
  "ArrowLeft" |
  "ArrowUpFromLine" |
  "ArrowUpSmall" |
  "Bank" |
  "Bell" |
  "Bolt" |
  "BookmarkFill" |
  "BookmarkStar" |
  "Briefcase" |
  "BriefcaseCheck" |
  "BriefcaseMoney" |
  "BriefcasePlus" |
  "BuildingsAlt" |
  "Calendar" |
  "CalendarCheckAlt" |
  "Camera" |
  "ChatDots" |
  "ChatText" |
  "Check" |
  "Checkbox" |
  "CheckCircle" |
  "CheckCircle2" |
  "CheckDouble" |
  "CheckSquare" |
  "ClipboardPlus" |
  "Coins" |
  "CommentLock" |
  "Copy" |
  "CopyAlt" |
  "CreditCard" |
  "CreditCardCheck" |
  "CreditCardConvert" |
  "CreditCardEdit" |
  "CreditCardPlus" |
  "CreditCardSlash" |
  "Cross" |
  "Document" |
  "DocumentList" |
  "DocumentListSmall" |
  "Edit" |
  "Exchange" |
  "ExchangeHorizontal" |
  "ExclamationCircle" |
  "Eye" |
  "EyeSlash" |
  "FaildIcon" |
  "FilePdf" |
  "FilterPlus" |
  "FingerPrint" |
  "Gallery" |
  "GasWhite" |
  "Gift" |
  "Globe" |
  "HeadPhones" |
  "Home" |
  "IconRotateRight90" |
  "IdCard" |
  "ImageGallery" |
  "Invoice" |
  "Key" |
  "KeyCircle" |
  "LayerGroup" |
  "Line" |
  "LocationPin" |
  "LogOut" |
  "Message" |
  "MessageText" |
  "Messagestext2" |
  "Mobile" |
  "MoneyBill" |
  "MoneyBillBan" |
  "MoneyBillCheck" |
  "MoneyBillConvert" |
  "MoneyBillReceive" |
  "MoneyBills" |
  "MoneyBillSearch" |
  "MoneyBillSend" |
  "MoneyBillTimes" |
  "MoneyWithdrawal" |
  "Moon" |
  "MoreHorizontal" |
  "MoreVertical" |
  "MyLoan" |
  "Nut" |
  "Pen" |
  "PenLine" |
  "PhoneOffice" |
  "Pin" |
  "PinLight" |
  "Plus" |
  "PlusCircle" |
  "Post" |
  "QuestionCircle" |
  "RadioButton" |
  "RecepieSearch" |
  "Rial" |
  "Rial2" |
  "Rotate" |
  "RotateRight" |
  "Scale" |
  "ScanQr" |
  "Search" |
  "SearchText" |
  "Share" |
  "ShieldCheck" |
  "ShieldQuestion" |
  "SimCard" |
  "SlidersHorizontal" |
  "SlidersHorizontalAlt" |
  "Star" |
  "Sun" |
  "Trash" |
  "TriangleExclamation" |
  "Truck" |
  "Unlock" |
  "User" |
  "User2" |
  "UserChange" |
  "UserCircle" |
  "UserOutline" |
  "UserPlus" |
  "UserSearch" |
  "UserSquare" |
  "Vector" |
  "Video" |
  "Voicemail"
  ;