export interface IIconProps {
  color?: string;
  size?: number | string;
};


export type TIconName =
  "ActivitySquare" |
  "AddressBook" |
  "AddressBookRegular" |
  "AngleDown" |
  "AngleLeft" |
  "AngleLeftSmall" |
  "AngleRight" |
  "AnglesDownSmall" |
  "AnglesUpSmall" |
  "AngleDownSmall" |
  "ArrowDownFromLine" |
  "ArrowDownSmall" |
  "ArrowLeft" |
  "ArrowUpFromLine" |
  "ArrowUpSmall" |
  "Bank" |
  "BankFilled" |
  "Bell" |
  "Bolt" |
  "BookmarkStarFill" |
  "BookmarkStar" |
  "BriefcaseRegular" |
  "Document" |
  "DocumentFilled" |
  "DocumentList" |
  "DocumentRegular" |
  "Briefcase" |
  "BriefcaseCheck" |
  "BriefcaseMoney" |
  "BriefcaseMoneyRegular" |
  "BriefcasePlus" |
  "BriefcasePlusRegular" |
  "BuildingsAlt" |
  "Calendar" |
  "CalendarCheckAlt" |
  "Camera" |
  "CaretLeftFilled" |
  "ChatText" |
  "ChatDots" |
  "Check" |
  "CheckCircleFilled" |
  "CheckDouble" |
  "CheckSquare" |
  "CheckSquareFilled" |
  "ClipboardPlus" |
  "Coins" |
  "CoinsRegular" |
  "CommentLock" |
  "CopyAlt" |
  "CreditCard" |
  "CreditCardRegular" |
  "CreditCardFilled" |
  "CreditCardCheck" |
  "CreditCardConvert" |
  "CreditCardConvertFilled" |
  "CreditCardEdit" |
  "CreditCardPlus" |
  "CreditCardPlusRegular" |
  "CreditCardSlash" |
  "Document" |
  "Edit" |
  "EditRegular" |
  "ExchangeHorizontalFilled" |
  "ExchangeHorizontal" |
  "ExchangeHorizontalRegular" |
  "InfoCircleFilled" |
  "Eye" |
  "EyeSlash" |
  "FilePdf" |
  "FilterPlus" |
  "FingerPrint" |
  "FileTextSearch" |
  "FileTextSearchRegular" |
  "Gas" |
  "Gift" |
  "GiftFilled" |
  "GlobeRegular" |
  "Globe" |
  "HeadPhones" |
  "Home" |
  "HomeRegular" |
  "HomeFilled" |
  "IdCard" |
  "ImageGallery" |
  "Invoice" |
  "Irancell" |
  "Key" |
  "KeyCircle" |
  "LayerGroup" |
  "LocationPin" |
  "LocationPinRegular" |
  "LogOut" |
  "Mci" |
  "Message" |
  "MessageRegular" |
  "MessageText" |
  "MessagesText" |
  "Mobile" |
  "MoneyBill" |
  "MoneyBillBan" |
  "MoneyBillCheck" |
  "MoneyBillConvert" |
  "MoneyBillConvertFilled" |
  "MoneyBillReceive" |
  "MoneyBills" |
  "MoneyBillSearch" |
  "MoneyBillSend" |
  "MoneyBillTimes" |
  "MoneyWithdrawal" |
  "Moon" |
  "MoreHorizontal" |
  "MoreVertical" |
  "Nut" |
  "Pen" |
  "PenLineRegular" |
  "PenLine" |
  "PhoneOffice" |
  "Pin" |
  "PinFilled" |
  "Plus" |
  "PlusCircle" |
  "PlusCircleFilled" |
  "Power" |
  "BoxSearch" |
  "QuestionCircle" |
  "QuestionCircleFilled" |
  "RadioButton" |
  "RecepieSearch" |
  "RecepieSearchRegular" |
  "Rightel" |
  "Rotate" |
  "Rightel" |
  "RotateRight" |
  "SamanTel" |
  "Scale" |
  "ScanQr" |
  "Search" |
  "SearchText" |
  "Share" |
  "Shatel" |
  "ShieldCheck" |
  "ShieldQuestionFilled" |
  "SimCardFilled" |
  "AddSimCard" |
  "SlidersHorizontal" |
  "SlidersHorizontalRegular" |
  "SlidersHorizontalAlt" |
  "StarOutlined" |
  "StarFilled" |
  "Sun" |
  "Tel" |
  "Trash" |
  "Times" |
  "TimesCircle" |
  "TimesCircleFilled" |
  "TriangleExclamationFilled" |
  "Truck" |
  "Unlock" |
  "User" |
  "UserRegular" |
  "UserFilled" |
  "UserChange" |
  "UserCircle" |
  "UserPlus" |
  "UserSearch" |
  "UserSquare" |
  "Video" |
  "VideoRegular" |
  "VideoFilled" |
  "Voicemail" |
  "Water"
  ;